name: Cargo

on:
  - push
  - pull_request

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CI: "1"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: component
        uses: actions-rs/components-nightly@v1
        with:
          component: clippy

      - uses: actions-rs/toolchain@v1
        with:
            override: true
            toolchain: ${{ steps.component.outputs.toolchain }}

      - name: Run tests
        run: cargo test --verbose
